language: node_js

#node_js:
#  - "7"
#  - "6"
#  - "stable"

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "6"
#    - os: linux
#      node_js: "4.3"
      
    - os: osx
      node_js: "8"
    - os: osx
      node_js: "7"
    - os: osx
      node_js: "6"
#    - os: osx
#      node_js: "4.3"

before_script:
  - pwd
  - ls -la
  - cp install/install.js .
  - node install.js --onlyFix --app_dir=app --react_dir=react --web_dir=docs --root=".." --app_name=test-app
  - cp app/config.js.dist app/config.js
  - cp react/config.js.dist react/config.js
  - cd react
  - yarn
  - export WEBPACK_MODE=dev
  - echo $WEBPACK_MODE
  - yarn devnowatch
  - pwd
  - node index.server.js 1>> log.log 2>>log.log & disown
  - sleep 3
  - cat log.log
  - cd ..
  - echo 'after devnowatch in before' && ls -la docs/dist/

script:
  - pwd
  - echo 'after devnowatch in script' && ls -la docs/dist/
  - export WEBPACK_MODE=dev
  - echo $WEBPACK_MODE
  - yarn test
  - rm -rf docs/dist/*
  - cd react
  - yarn prod
  - sudo kill -SIGTERM $(ps aux | grep "index.server.js" | grep -v grep | head -1 | awk '{print $2}')
  - node index.server.js 1>> log2.log 2>>log2.log & disown
  - sleep 3
  - cat log2.log
  - cd ..
  - echo 'after prod' && ls -la docs/dist/
  - export WEBPACK_MODE=prod
  - echo $WEBPACK_MODE
  - yarn test
  - /bin/bash test/testinstall.sh

