language: node_js

#node_js:
#  - "7"
#  - "6"
#  - "stable"

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "6"
#    - os: linux
#      node_js: "4.3"
      
    - os: osx
      node_js: "8"
    - os: osx
      node_js: "7"
    - os: osx
      node_js: "6"
#    - os: osx
#      node_js: "4.3"

script:
  - /bin/bash test/testinstall.sh ___testdir1 v0.1.0 react docs app "--root=.. --app_name=test-app --jwtsecret=secret --travis"
  - /bin/bash test/testinstall.sh ___testdir2 v0.1.0 react-notdefault docs-notdefault app-notdefault "--root=.. --app_name=test-app2 --jwtsecret=secret --travis"

