# https://hub.docker.com/_/nginx/
# https://gist.github.com/michaelneu/2ca7987ef00fa3fbe4fd7b9c07834cc7
# !!! finally worked php: http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/comment-page-1/
web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
#  environment:
#   - NGINX_HOST=localhost
#   - NGINX_PORT=9000
#  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
php:
    image: php:7-fpm
    volumes:
        - ./code:/code

# run
# docker-compose up
# and then open in browser
# http://localhost:8080/test.php