
/* types */

export const HOME_INTRO_REQUEST = 'HOME_INTRO_REQUEST';
export const HOME_INTRO_SUCCESS = 'HOME_INTRO_SUCCESS';
export const HOME_INTRO_FAILURE = 'HOME_INTRO_FAILURE';

export const HOME_COMMUNITY_REQUEST = 'HOME_COMMUNITY_REQUEST';
export const HOME_COMMUNITY_SUCCESS = 'HOME_COMMUNITY_SUCCESS';
export const HOME_COMMUNITY_FAILURE = 'HOME_COMMUNITY_FAILURE';

export const HOME_INDEPENDENT_REQUEST = 'HOME_INDEPENDENT_REQUEST';
export const HOME_INDEPENDENT_SUCCESS = 'HOME_INDEPENDENT_SUCCESS';
export const HOME_INDEPENDENT_FAILURE = 'HOME_INDEPENDENT_FAILURE';

export const HOME_CURRENT_REQUEST = 'HOME_CURRENT_REQUEST';
export const HOME_CURRENT_SUCCESS = 'HOME_CURRENT_SUCCESS';
export const HOME_CURRENT_FAILURE = 'HOME_CURRENT_FAILURE';

export const HOME_PARTNERSHIPS_REQUEST = 'HOME_PARTNERSHIPS_REQUEST';
export const HOME_PARTNERSHIPS_SUCCESS = 'HOME_PARTNERSHIPS_SUCCESS';
export const HOME_PARTNERSHIPS_FAILURE = 'HOME_PARTNERSHIPS_FAILURE';

export const HOME_AGILE_REQUEST = 'HOME_AGILE_REQUEST';
export const HOME_AGILE_SUCCESS = 'HOME_AGILE_SUCCESS';
export const HOME_AGILE_FAILURE = 'HOME_AGILE_FAILURE';

export const HOME_ADVISORS_REQUEST = 'HOME_ADVISORS_REQUEST';
export const HOME_ADVISORS_SUCCESS = 'HOME_ADVISORS_SUCCESS';
export const HOME_ADVISORS_FAILURE = 'HOME_ADVISORS_FAILURE';

export const HOME_PARTNERS_REQUEST = 'HOME_PARTNERS_REQUEST';
export const HOME_PARTNERS_SUCCESS = 'HOME_PARTNERS_SUCCESS';
export const HOME_PARTNERS_FAILURE = 'HOME_PARTNERS_FAILURE';

export const HOME_OPEN_REQUEST = 'HOME_OPEN_REQUEST';
export const HOME_OPEN_SUCCESS = 'HOME_OPEN_SUCCESS';
export const HOME_OPEN_FAILURE = 'HOME_OPEN_FAILURE';

export const PROGRAMS_PHYSICIAN_REQUEST = 'PROGRAMS_PHYSICIAN_REQUEST';
export const PROGRAMS_PHYSICIAN_SUCCESS = 'PROGRAMS_PHYSICIAN_SUCCESS';
export const PROGRAMS_PHYSICIAN_FAILURE = 'PROGRAMS_PHYSICIAN_FAILURE';

export const PROGRAMS_AWARENESS_REQUEST = 'PROGRAMS_AWARENESS_REQUEST';
export const PROGRAMS_AWARENESS_SUCCESS = 'PROGRAMS_AWARENESS_SUCCESS';
export const PROGRAMS_AWARENESS_FAILURE = 'PROGRAMS_AWARENESS_FAILURE';

export const PROGRAMS_PATIENT_REQUEST = 'PROGRAMS_PATIENT_REQUEST';
export const PROGRAMS_PATIENT_SUCCESS = 'PROGRAMS_PATIENT_SUCCESS';
export const PROGRAMS_PATIENT_FAILURE = 'PROGRAMS_PATIENT_FAILURE';

export const PROGRAMS_RESEARCHER_REQUEST = 'PROGRAMS_RESEARCHER_REQUEST';
export const PROGRAMS_RESEARCHER_SUCCESS = 'PROGRAMS_RESEARCHER_SUCCESS';
export const PROGRAMS_RESEARCHER_FAILURE = 'PROGRAMS_RESEARCHER_FAILURE';

export const FOOTER_REQUEST = 'FOOTER_REQUEST';
export const FOOTER_SUCCESS = 'FOOTER_SUCCESS';
export const FOOTER_FAILURE = 'FOOTER_FAILURE';

export const HEADER_REQUEST = 'HEADER_REQUEST';
export const HEADER_SUCCESS = 'HEADER_SUCCESS';
export const HEADER_FAILURE = 'HEADER_FAILURE';

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST';
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS';
export const CONTACT_DETAILS_FAILURE = 'CONTACT_DETAILS_FAILURE';
/* types */
